// Mock data para desenvolvimento — substituir por queries Prisma após setup do banco

export const CATEGORIES = [
  { id: "1", name: "Elétrica", slug: "eletrica", icon: "⚡" },
  { id: "2", name: "Hidráulica", slug: "hidraulica", icon: "🔧" },
  { id: "3", name: "Limpeza", slug: "limpeza", icon: "🧹" },
  { id: "4", name: "Jardinagem", slug: "jardinagem", icon: "🌿" },
  { id: "5", name: "Montagem", slug: "montagem", icon: "🛠️" },
  { id: "6", name: "Pintura", slug: "pintura", icon: "🎨" },
  { id: "7", name: "Ar-cond.", slug: "ar-condicionado", icon: "❄️" },
  { id: "8", name: "Reparos", slug: "reparos", icon: "🔨" },
];

export const PROVIDERS = [
  {
    id: "1",
    name: "Carlos Mendes",
    category: "Elétrica",
    categorySlug: "eletrica",
    rating: 4.9,
    totalReviews: 142,
    price: "R$ 80",
    priceType: "por hora",
    verified: true,
    image: null,
    bio: "Eletricista com 12 anos de experiência. Especialista em instalações residenciais e prediais.",
    compliments: ["Pontual", "Organizado", "Profissional"],
    services: [
      { name: "Instalação de tomada", price: "R$ 60" },
      { name: "Troca de disjuntor", price: "R$ 80" },
      { name: "Instalação de luminária", price: "R$ 70" },
      { name: "Revisão elétrica geral", price: "R$ 200" },
    ],
  },
  {
    id: "2",
    name: "Ana Lima",
    category: "Limpeza",
    categorySlug: "limpeza",
    rating: 5.0,
    totalReviews: 89,
    price: "R$ 120",
    priceType: "diária",
    verified: true,
    image: null,
    bio: "Especialista em limpeza residencial profunda e organização. Trabalho com produtos premium.",
    compliments: ["Cuidadosa", "Detalhista", "Confiável"],
    services: [
      { name: "Limpeza básica", price: "R$ 120" },
      { name: "Limpeza profunda", price: "R$ 220" },
      { name: "Limpeza pós-obra", price: "R$ 350" },
      { name: "Organização de cozinha", price: "R$ 150" },
    ],
  },
  {
    id: "3",
    name: "Rafael Santos",
    category: "Hidráulica",
    categorySlug: "hidraulica",
    rating: 4.8,
    totalReviews: 67,
    price: "R$ 90",
    priceType: "por hora",
    verified: true,
    image: null,
    bio: "Encanador com foco em reparos rápidos e instalações de qualidade. Atendo emergências.",
    compliments: ["Rápido", "Honesto", "Eficiente"],
    services: [
      { name: "Desentupimento", price: "R$ 90" },
      { name: "Troca de torneira", price: "R$ 70" },
      { name: "Reparo de vazamento", price: "R$ 100" },
      { name: "Instalação de chuveiro", price: "R$ 120" },
    ],
  },
  {
    id: "4",
    name: "Mariana Costa",
    category: "Jardinagem",
    categorySlug: "jardinagem",
    rating: 4.7,
    totalReviews: 34,
    price: "R$ 150",
    priceType: "visita",
    verified: false,
    image: null,
    bio: "Paisagista e jardineira. Cuido do seu jardim com carinho e técnica.",
    compliments: ["Criativa", "Cuidadosa"],
    services: [
      { name: "Poda e manutenção", price: "R$ 150" },
      { name: "Plantio e vasos", price: "R$ 200" },
      { name: "Paisagismo", price: "R$ 400" },
    ],
  },
];

export const ORDERS_MOCK = [
  {
    id: "ord1",
    provider: PROVIDERS[0],
    service: "Instalação de tomada",
    status: "COMPLETED",
    scheduledAt: "2026-03-10T14:00:00",
    total: "R$ 60",
    paidViaClub: false,
  },
  {
    id: "ord2",
    provider: PROVIDERS[1],
    service: "Limpeza profunda",
    status: "CONFIRMED",
    scheduledAt: "2026-03-25T09:00:00",
    total: "R$ 220",
    paidViaClub: true,
  },
];
